name: mockup_one
description: "A new Flutter project for mockup app trading"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  get: ^4.6.6
  intl: ^0.19.0
  syncfusion_flutter_charts: ^24.2.9
  lottie: ^3.1.0
  # intl_phone_number_input: ^0.7.4
  otp_text_field: ^1.1.3
  # flutter_libphonenumber: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/flags/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter/static/Inter-ExtraBold.ttf
    - family: Andika
      fonts:
        - asset: assets/fonts/Andika/Andika-Regular.ttf
